In [15]:
#Build the game attribute master
ap=r'C:\EveriTools\Workspace\Code\DemandForeCast\Data\processed\game_attr_cleaned.csv'
sp=r'C:\EveriTools\Workspace\Code\DemandForeCast\Data\processed\sales_clean.csv'
mp=r'C:\EveriTools\Workspace\Code\DemandForeCast\Data\processed\mapping_clean.csv'
bp=r"C:\EveriTools\Workspace\Code\DemandForeCast\Data\raw sample\IGT_Everi_Attributes.xlsx"
ep=r"C:\EveriTools\Workspace\Code\DemandForeCast\Data\processed\performance_aggregated.csv"

In [16]:
import pandas as pd

ap_df = pd.read_csv(ap)
sp_df = pd.read_csv(sp)
mp_df = pd.read_csv(mp)
bp_df = pd.read_excel(bp)
ep_df = pd.read_csv(ep)

print('game_attr_cleaned.csv head:')
display(ap_df.head())

print('sales_clean.csv head:')
display(sp_df.head())

C:\Users\jbv35354\AppData\Local\Temp\ipykernel_22124\3752837830.py:7: DtypeWarning: Columns (4,5,41) have mixed types. Specify dtype option on import or set low_memory=False.
  ep_df = pd.read_csv(ep)

game_attr_cleaned.csv head:

,theme_sk,theme_nk,source_system_cd,source_company_cd,theme_name,theme_name_friendly,family_name,math_model_family,product_family,game_type,...,audit_created_by,audit_created_date,audit_modified_by,audit_modified_date,audit_is_deleted,game_matrix_bingo,game_matrix_hhr_exacta,game_matrix_lottery,game_matrix_prize_first_slot,game_matrix_reels_first_slot
0,1,0000,ATLASSIAN,EVERI,InitialRelease_Template_GameTitle,InitialRelease_Template_GameTitle,NaN,NaN,Standard Video,Not Banked,...,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23T17:07:49.405Z,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23T17:07:49.405Z,False,False,False,False,False,False
1,2,10000,ATLASSIAN,EVERI,Tourney Now Star Struck,Tourney Now Star Struck,NaN,['Reels First Slot'],TE ORT,Not Banked,...,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23T17:07:49.405Z,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23T17:07:49.405Z,False,False,False,False,False,True
2,3,10003,ATLASSIAN,EVERI,Little Shop of Horrors - Flex HHR,Little Shop of Horrors - Flex HHR,NaN,['HHR [Exacta]'],Standard Video,Not Banked,...,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23T17:07:49.405Z,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23T17:07:49.405Z,False,False,True,False,False,False
3,4,10005,ATLASSIAN,EVERI,Great Tiger Gold,Great Tiger Gold,NaN,"['Bingo', 'HHR [Exacta]', 'Lottery', 'Prize Fi...",Standard Video,Not Banked,...,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23T17:07:49.405Z,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23T17:07:49.405Z,False,True,True,True,True,False
4,5,10006,ATLASSIAN,EVERI,Octopus Gold,Octopus Gold,NaN,"['Bingo', 'HHR [Exacta]', 'Lottery', 'Prize Fi...",Standard Video,Not Banked,...,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23T17:07:49.405Z,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23T17:07:49.405Z,False,True,True,True,True,False

sales_clean.csv head:

,beginning_month_date,quarter_date,year_date,fiscal_year_period,theme_key,product,co_pa_account_assign_desc,external_internal_co_desc,material_group_desc,division_desc,...,ref_num_account_manager,ref_num_sales_director,director_stategic_accounts,corporate_account_number,corporate_account_name,ref_num_metrics_filter,ref_num_property_type,ref_num_market_type,ref_num_native_customer,ref_num_regional_vp
0,2022-01-01,q1,2022,z1/001/2023,f0y,#,new machine,external,not assigned,machine,...,jay porter,will shuirman,NaN,3117689.0,roadhouse casino elko,0.0,casino,commercial,False,pete kaufman
1,2016-08-01,q3,2016,z1/008/2017,rm8,s3000,new machine,external,machines,machine,...,tim centanzo,adam cascais,troy fenn,3700023.0,mgm resorts international,1.0,casino,commercial,False,kristin orcutt
2,2023-03-01,q1,2023,z1/003/2024,h7k,2558443,new machine,external,not assigned,machine,...,jj jarzynka,will shuirman,NaN,3121789.0,verdi grillhouse & casino,1.0,casino,commercial,False,pete kaufman
3,2011-03-01,q1,2011,z1/006/2011,#,trade-in credit,new machine,external,non machine fg,machine,...,jj jarzynka,will shuirman,NaN,3701380.0,"gpeg 1, llc",1.0,casino,commercial,False,pete kaufman
4,2023-09-01,q3,2023,z1/009/2024,jhs,add theme,new machine,external,machines,machine,...,vasilis stamopoulos,vasilis stamopoulos,NaN,3701564.0,max bet,1.0,casino,commercial,False,petko ivanov

In [14]:
ep_df.head()

,yearmonth,game_name,supplier,slot_cabinet_name,country,region,operator_type,own_status,game_category,game_classification,...,utilization_index_same_type_same_denom,avg_theo_net_win_index_vs_house,avg_theo_net_win_index_vs_zone,avg_state_casino_count,parent_supplier,parent_own_status,parent_game,game_release_date,cabinet_release_date,state_count
0,2022-01-01,$25000 pyramid,igt,megatower,NaN,NaN,u.s. commercial casino,leased,mechanical reel,class 3,...,1.265000,2.510000,2.215000,NaN,igt,premium,NaN,2021-05-01,2017-05-01,3
1,2022-01-01,$25000 pyramid,igt,megatower,NaN,NaN,u.s. tribal casino,leased,mechanical reel,class 3,...,0.570000,0.520000,0.700000,NaN,igt,premium,NaN,2021-05-01,2017-05-01,1
2,2022-01-01,10 play poker,igt,avp slant,NaN,NaN,u.s. commercial casino,owned,video poker,class 3,...,1.210000,1.890000,2.010000,NaN,igt,core,NaN,2017-10-01,2005-07-01,1
3,2022-01-01,10 play poker,igt,game king,NaN,NaN,u.s. commercial casino,owned,video poker,class 3,...,0.460000,0.764545,0.948182,NaN,igt,core,NaN,2017-10-01,2001-07-01,3
4,2022-01-01,10 play poker,igt,game king,NaN,NaN,u.s. tribal casino,leased,video poker,class 3,...,0.447143,0.771429,0.960000,NaN,igt,core,NaN,2017-10-01,2001-07-01,2

In [9]:
target_companies = {
    'igt canada',
    'igt canada solutions ulc',
    'igt n.a.'
}

sp_df_filtered = sp_df[
    sp_df['company_code_desc'].str.strip().str.lower().isin(target_companies)
    & (sp_df['co_pa_account_assign_desc'].str.strip().str.lower() == 'new machine')
]

display(sp_df_filtered)
print(f"Filtered rows: {len(sp_df_filtered)}")

,beginning_month_date,quarter_date,year_date,fiscal_year_period,theme_key,product,co_pa_account_assign_desc,external_internal_co_desc,material_group_desc,division_desc,...,ref_num_account_manager,ref_num_sales_director,director_stategic_accounts,corporate_account_number,corporate_account_name,ref_num_metrics_filter,ref_num_property_type,ref_num_market_type,ref_num_native_customer,ref_num_regional_vp
0,2022-01-01,q1,2022,z1/001/2023,f0y,#,new machine,external,not assigned,machine,...,jay porter,will shuirman,NaN,3117689.0,roadhouse casino elko,0.0,casino,commercial,False,pete kaufman
1,2016-08-01,q3,2016,z1/008/2017,rm8,s3000,new machine,external,machines,machine,...,tim centanzo,adam cascais,troy fenn,3700023.0,mgm resorts international,1.0,casino,commercial,False,kristin orcutt
2,2023-03-01,q1,2023,z1/003/2024,h7k,2558443,new machine,external,not assigned,machine,...,jj jarzynka,will shuirman,NaN,3121789.0,verdi grillhouse & casino,1.0,casino,commercial,False,pete kaufman
3,2011-03-01,q1,2011,z1/006/2011,#,trade-in credit,new machine,external,non machine fg,machine,...,jj jarzynka,will shuirman,NaN,3701380.0,"gpeg 1, llc",1.0,casino,commercial,False,pete kaufman
5,2014-04-01,q2,2014,z1/007/2014,ll4,univ_mld_slant,new machine,external,machines,machine,...,brielle pastore,kristina klickovich,NaN,3700032.0,carnival corporation,1.0,cruise ship,commercial,False,kristin orcutt
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2343,2008-01-01,q1,2008,z1/004/2008,t15,gk_17,new machine,external,machines,machine,...,kieran hughes,NaN,NaN,3701131.0,"jlj, inc.",0.0,NaN,vlt,False,NaN
2345,2020-11-01,q4,2020,z1/011/2021,tsd,#,new machine,external,not assigned,machine,...,michael caldrone,will shuirman,NaN,3100834.0,casino royale,1.0,casino,commercial,False,pete kaufman
2346,2026-01-01,q1,2026,z1/001/2027,j0h,#,new machine,external,not assigned,machine,...,jay porter,will shuirman,NaN,3116105.0,roadhouse casino,0.0,casino,commercial,False,pete kaufman
2347,2009-12-01,q4,2009,z1/003/2010,cy5,g20,new machine,external,machines,machine,...,bruce swanson,jim kaffenberger,NaN,3106095.0,gaming capital group,1.0,casino,commercial,True,pete kaufman
2348,2019-04-01,q2,2019,z1/004/2020,h5i,2442427,new machine,external,not assigned,machine,...,bruce swanson,jim kaffenberger,NaN,3106095.0,gaming capital group,1.0,casino,commercial & bingo,True,pete kaufman

Filtered rows: 1580

In [11]:
ap_df_lower = ap_df.copy()

# Lowercase all column names
ap_df_lower.columns = ap_df_lower.columns.str.strip().str.lower()

# Lowercase all string values
for col in ap_df_lower.select_dtypes(include='object').columns:
    ap_df_lower[col] = ap_df_lower[col].str.strip().str.lower()

ap_df_filtered = ap_df_lower[
    ap_df_lower['source_company_cd'] == 'igt'
]

display(ap_df_filtered)
print(f"Filtered rows: {len(ap_df_filtered)}")

,theme_sk,theme_nk,source_system_cd,source_company_cd,theme_name,theme_name_friendly,family_name,math_model_family,product_family,game_type,...,audit_created_by,audit_created_date,audit_modified_by,audit_modified_date,audit_is_deleted,game_matrix_bingo,game_matrix_hhr_exacta,game_matrix_lottery,game_matrix_prize_first_slot,game_matrix_reels_first_slot
249,250,10x,airtable,igt,10x,10x,not established,NaN,s3k,spinning reel,...,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23t17:07:49.405z,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23t17:07:49.405z,False,False,False,False,False,False
511,512,1ft,airtable,igt,1ft,1ft,not established,NaN,peak bartop/crystalseries,video,...,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23t17:07:49.405z,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23t17:07:49.405z,False,False,False,False,False,False
590,591,3wa,airtable,igt,3wa,3wa,NaN,NaN,poker asc video,video,...,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23t17:07:49.405z,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23t17:07:49.405z,False,False,False,False,False,False
591,592,3wd,airtable,igt,3wd,3wd,not established,NaN,s3k,spinning reel,...,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23t17:07:49.405z,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23t17:07:49.405z,False,False,False,False,False,False
592,593,3wm,airtable,igt,3wm,3wm,not established,NaN,poker asc video,video,...,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23t17:07:49.405z,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23t17:07:49.405z,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3784,3785,6v8,airtable,igt,6v8,6v8,NaN,NaN,other,video,...,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23t17:07:49.405z,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23t17:07:49.405z,False,False,False,False,False,False
3785,3786,6v9,airtable,igt,6v9,6v9,not established,NaN,dual asc video,video,...,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23t17:07:49.405z,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23t17:07:49.405z,False,False,False,False,False,False
3786,3787,6va,airtable,igt,6va,6va,not established,NaN,dual asc video,video,...,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23t17:07:49.405z,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23t17:07:49.405z,False,False,False,False,False,False
3787,3788,6vb,airtable,igt,6vb,6vb,not established,NaN,dual asc video,video,...,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23t17:07:49.405z,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23t17:07:49.405z,False,False,False,False,False,False
4290,4291,7tp,airtable,igt,7tp,7tp,not established,NaN,s3k,spinning reel,...,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23t17:07:49.405z,1e787607-5ff7-4bfc-9ebc-694c2e5869f9,2026-06-23t17:07:49.405z,False,False,False,False,False,False

Filtered rows: 1798

In [ ]:
ap_df

In [20]:
# Join ap_df(theme_nk) to sp_df(theme_key)
ap_join = ap_df.copy()
sp_join = sp_df.copy()

ap_join['theme_nk_join'] = ap_join['theme_nk'].astype(str).str.strip().str.lower()
sp_join['theme_key_join'] = sp_join['theme_key'].astype(str).str.strip().str.lower()

joined_df = ap_join.merge(
    sp_join,
    left_on='theme_nk_join',
    right_on='theme_key_join',
    how='inner',
    suffixes=('_ap', '_sp')
)

display(joined_df.head())
print(f"Joined rows: {len(joined_df)}")

,theme_sk,theme_nk,source_system_cd,source_company_cd,theme_name_ap,theme_name_friendly,family_name,math_model_family,product_family,game_type_ap,...,theme_key_id,theme_name_mp,game_type_mp,game_sub_type,business_segment,cabinet_desc,theme_key,created_on,updated_on,theme_key_join
0,591,3WA,AIRTABLE,IGT,3WA,3WA,NaN,NaN,Poker ASC Video,Video,...,10687,3 way action poker,NaN,NaN,NaN,crystalslant,3wa,44:10.8,54:20.0,3wa
1,591,3WA,AIRTABLE,IGT,3WA,3WA,NaN,NaN,Poker ASC Video,Video,...,11990,3 way action poker,NaN,NaN,NaN,game king,3wa,44:10.8,54:20.0,3wa
2,591,3WA,AIRTABLE,IGT,3WA,3WA,NaN,NaN,Poker ASC Video,Video,...,12089,3 way action poker,NaN,NaN,NaN,g20 upright,3wa,44:10.8,54:20.0,3wa
3,591,3WA,AIRTABLE,IGT,3WA,3WA,NaN,NaN,Poker ASC Video,Video,...,12442,3 way action poker,NaN,NaN,NaN,g23 upright,3wa,44:10.8,54:20.0,3wa
4,591,3WA,AIRTABLE,IGT,3WA,3WA,NaN,NaN,Poker ASC Video,Video,...,14335,3 way action poker,NaN,NaN,NaN,NaN,3wa,44:10.8,54:20.0,3wa

Joined rows: 234

In [22]:
# Join ap_df(theme_nk) to mp_df(theme_key)
ap_join_mp = ap_df.copy()
mp_join = mp_df.copy()

ap_join_mp['theme_nk_join'] = ap_join_mp['theme_nk'].astype(str).str.strip().str.lower()
mp_join['theme_key_join'] = mp_join['theme_key'].astype(str).str.strip().str.lower()

joined_df_mp = ap_join_mp.merge(
    mp_join,
    left_on='theme_nk_join',
    right_on='theme_key_join',
    how='inner',
    suffixes=('_ap', '_mp')
)

display(joined_df_mp.head())
print(f"Joined rows: {len(joined_df_mp)}")

,theme_sk,theme_nk,source_system_cd,source_company_cd,theme_name_ap,theme_name_friendly,family_name,math_model_family,product_family,game_type_ap,...,theme_key_id,theme_name_mp,game_type_mp,game_sub_type,business_segment,cabinet_desc,theme_key,created_on,updated_on,theme_key_join
0,591,3WA,AIRTABLE,IGT,3WA,3WA,NaN,NaN,Poker ASC Video,Video,...,10687,3 way action poker,NaN,NaN,NaN,crystalslant,3wa,44:10.8,54:20.0,3wa
1,591,3WA,AIRTABLE,IGT,3WA,3WA,NaN,NaN,Poker ASC Video,Video,...,11990,3 way action poker,NaN,NaN,NaN,game king,3wa,44:10.8,54:20.0,3wa
2,591,3WA,AIRTABLE,IGT,3WA,3WA,NaN,NaN,Poker ASC Video,Video,...,12089,3 way action poker,NaN,NaN,NaN,g20 upright,3wa,44:10.8,54:20.0,3wa
3,591,3WA,AIRTABLE,IGT,3WA,3WA,NaN,NaN,Poker ASC Video,Video,...,12442,3 way action poker,NaN,NaN,NaN,g23 upright,3wa,44:10.8,54:20.0,3wa
4,591,3WA,AIRTABLE,IGT,3WA,3WA,NaN,NaN,Poker ASC Video,Video,...,14335,3 way action poker,NaN,NaN,NaN,NaN,3wa,44:10.8,54:20.0,3wa

Joined rows: 234

In [23]:
joined_df_mp

,theme_sk,theme_nk,source_system_cd,source_company_cd,theme_name_ap,theme_name_friendly,family_name,math_model_family,product_family,game_type_ap,...,theme_key_id,theme_name_mp,game_type_mp,game_sub_type,business_segment,cabinet_desc,theme_key,created_on,updated_on,theme_key_join
0,591,3WA,AIRTABLE,IGT,3WA,3WA,NaN,NaN,Poker ASC Video,Video,...,10687,3 way action poker,NaN,NaN,NaN,crystalslant,3wa,44:10.8,54:20.0,3wa
1,591,3WA,AIRTABLE,IGT,3WA,3WA,NaN,NaN,Poker ASC Video,Video,...,11990,3 way action poker,NaN,NaN,NaN,game king,3wa,44:10.8,54:20.0,3wa
2,591,3WA,AIRTABLE,IGT,3WA,3WA,NaN,NaN,Poker ASC Video,Video,...,12089,3 way action poker,NaN,NaN,NaN,g20 upright,3wa,44:10.8,54:20.0,3wa
3,591,3WA,AIRTABLE,IGT,3WA,3WA,NaN,NaN,Poker ASC Video,Video,...,12442,3 way action poker,NaN,NaN,NaN,g23 upright,3wa,44:10.8,54:20.0,3wa
4,591,3WA,AIRTABLE,IGT,3WA,3WA,NaN,NaN,Poker ASC Video,Video,...,14335,3 way action poker,NaN,NaN,NaN,NaN,3wa,44:10.8,54:20.0,3wa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,3563,6MJ,AIRTABLE,IGT,6MJ,6MJ,Not Established,NaN,Other,Video,...,22587,icy wilds,NaN,NaN,NaN,universal slant,6mj,44:10.8,54:20.0,6mj
230,3563,6MJ,AIRTABLE,IGT,6MJ,6MJ,Not Established,NaN,Other,Video,...,22590,icy wilds,NaN,NaN,NaN,prodigi vu,6mj,44:10.8,54:20.0,6mj
231,3563,6MJ,AIRTABLE,IGT,6MJ,6MJ,Not Established,NaN,Other,Video,...,22740,icy wilds,NaN,NaN,NaN,smld,6mj,44:10.8,54:20.0,6mj
232,3646,6QK,AIRTABLE,IGT,6QK,6QK,Not Established,NaN,Cobalt27,Video,...,14387,fu gui hao men glorious fortunes,NaN,NaN,NaN,peak slant 32,6qk,44:10.8,NaN,6qk
233,3676,6RL,AIRTABLE,IGT,6RL,6RL,Not Established,NaN,Cobalt27,Video,...,24450,book of sophia,NaN,NaN,NaN,peak slant 32,6rl,24:25.9,NaN,6rl

In [19]:
# Coverage of Everi game themes between ep_df and bp_df using game-name join

# Normalize key columns for robust joining
ep_work = ep_df.copy()
bp_work = bp_df.copy()

# Helper for case-insensitive column lookup
def _find_col(df, candidates):
    lookup = {str(c).strip().lower(): c for c in df.columns}
    for c in candidates:
        key = c.strip().lower()
        if key in lookup:
            return lookup[key]
    return None

ep_supplier_col = _find_col(ep_work, ['supplier'])
ep_game_col = _find_col(ep_work, ['game_name', 'game name'])
# EP has no explicit themename, so default to game name as theme identifier
ep_theme_col = _find_col(ep_work, ['themename', 'theme_name', 'theme name']) or ep_game_col
# BP uses Theme Name in this file; keep Game Name as first preference if present
bp_game_col = _find_col(bp_work, ['Game Name', 'game_name', 'game name', 'Theme Name', 'theme name'])

if not ep_supplier_col or not ep_game_col or not bp_game_col:
    print('Could not find required columns.')
    print('ep_df columns:', list(ep_work.columns))
    print('bp_df columns:', list(bp_work.columns))
    raise KeyError('Missing one or more required columns for analysis.')

ep_work['supplier_norm'] = ep_work[ep_supplier_col].astype(str).str.strip().str.lower()
ep_work['game_name_join'] = ep_work[ep_game_col].astype(str).str.strip().str.lower()
bp_work['game_name_join'] = bp_work[bp_game_col].astype(str).str.strip().str.lower()

# Restrict EP population to IGT/Everi, then isolate Everi for requested percentages
ep_igt_everi = ep_work[ep_work['supplier_norm'].isin(['igt', 'everi'])].copy()
ep_everi = ep_igt_everi[ep_igt_everi['supplier_norm'] == 'everi'].copy()

# Outer join gives left/right/inner populations via indicator
merged = ep_everi.merge(
    bp_work,
    on='game_name_join',
    how='outer',
    indicator=True,
    suffixes=('_ep', '_bp')
)

# Unique theme populations from EP side (theme identifier = ep_theme_col)
left_themes = set(merged.loc[merged['_merge'] == 'left_only', ep_theme_col].dropna().astype(str).str.strip())
inner_themes = set(merged.loc[merged['_merge'] == 'both', ep_theme_col].dropna().astype(str).str.strip())

everi_theme_universe = set(ep_everi[ep_theme_col].dropna().astype(str).str.strip())
right_unique_bp_games = merged.loc[merged['_merge'] == 'right_only', bp_game_col].dropna().astype(str).str.strip().nunique()

theme_total = len(everi_theme_universe)
unmatched_pct = (len(left_themes) / theme_total * 100) if theme_total else 0
matched_pct = (len(inner_themes) / theme_total * 100) if theme_total else 0
right_pct_vs_everi_theme_universe = (right_unique_bp_games / theme_total * 100) if theme_total else 0

summary = pd.DataFrame({
    'population': ['left_only (EP Everi unmatched)', 'inner (matched in both)', 'right_only (BP-only names)'],
    'count_unique': [len(left_themes), len(inner_themes), right_unique_bp_games],
    'pct_of_ep_everi_unique_theme_universe': [unmatched_pct, matched_pct, right_pct_vs_everi_theme_universe]
})

print('Using columns ->')
print(f"EP supplier: {ep_supplier_col} | EP game: {ep_game_col} | EP theme-id: {ep_theme_col} | BP game/theme: {bp_game_col}")
print('EP filtered suppliers:', sorted(ep_igt_everi['supplier_norm'].dropna().unique().tolist()))
print('EP Everi rows:', len(ep_everi))
print('EP Everi unique theme universe:', theme_total)
print()
print('Requested percentage: Everi unique themes NOT included in both (left_only)')
print(f"{len(left_themes)} / {theme_total} = {unmatched_pct:.2f}%")
print()
display(summary)

Using columns ->
EP supplier: supplier | EP game: game_name | EP theme-id: game_name | BP game/theme: Theme Name
EP filtered suppliers: ['everi', 'igt']
EP Everi rows: 114386
EP Everi unique theme universe: 800

Requested percentage: Everi unique themes NOT included in both (left_only)
791 / 800 = 98.88%

,population,count_unique,pct_of_ep_everi_unique_theme_universe
0,left_only (EP Everi unmatched),791,98.875
1,inner (matched in both),9,1.125
2,right_only (BP-only names),431,53.875

In [20]:
# Join stats for both IGT and Everi against BP

def supplier_join_stats(ep_source, bp_source, suppliers=('igt', 'everi')):
    ep_local = ep_source.copy()
    bp_local = bp_source.copy()

    def _find_col(df, candidates):
        lookup = {str(c).strip().lower(): c for c in df.columns}
        for c in candidates:
            key = c.strip().lower()
            if key in lookup:
                return lookup[key]
        return None

    ep_supplier_col = _find_col(ep_local, ['supplier'])
    ep_game_col = _find_col(ep_local, ['game_name', 'game name'])
    ep_theme_col = _find_col(ep_local, ['themename', 'theme_name', 'theme name']) or ep_game_col
    bp_game_col = _find_col(bp_local, ['Game Name', 'game_name', 'game name', 'Theme Name', 'theme name'])

    if not ep_supplier_col or not ep_game_col or not bp_game_col:
        raise KeyError('Missing required columns in EP/BP dataframes')

    ep_local['supplier_norm'] = ep_local[ep_supplier_col].astype(str).str.strip().str.lower()
    ep_local['game_name_join'] = ep_local[ep_game_col].astype(str).str.strip().str.lower()
    bp_local['game_name_join'] = bp_local[bp_game_col].astype(str).str.strip().str.lower()

    out = []
    for supplier in suppliers:
        ep_supplier_df = ep_local[ep_local['supplier_norm'] == supplier].copy()

        merged_supplier = ep_supplier_df.merge(
            bp_local,
            on='game_name_join',
            how='outer',
            indicator=True,
            suffixes=('_ep', '_bp')
        )

        left_themes = set(merged_supplier.loc[merged_supplier['_merge'] == 'left_only', ep_theme_col].dropna().astype(str).str.strip())
        inner_themes = set(merged_supplier.loc[merged_supplier['_merge'] == 'both', ep_theme_col].dropna().astype(str).str.strip())
        right_unique_bp_games = merged_supplier.loc[merged_supplier['_merge'] == 'right_only', bp_game_col].dropna().astype(str).str.strip().nunique()

        supplier_theme_universe = set(ep_supplier_df[ep_theme_col].dropna().astype(str).str.strip())
        theme_total = len(supplier_theme_universe)

        out.append({
            'supplier': supplier,
            'ep_rows': len(ep_supplier_df),
            'ep_unique_theme_universe': theme_total,
            'left_only_unique': len(left_themes),
            'left_only_pct': (len(left_themes) / theme_total * 100) if theme_total else 0,
            'inner_unique': len(inner_themes),
            'inner_pct': (len(inner_themes) / theme_total * 100) if theme_total else 0,
            'right_only_unique_bp_names': right_unique_bp_games,
            'right_only_pct_vs_ep_universe': (right_unique_bp_games / theme_total * 100) if theme_total else 0
        })

    return pd.DataFrame(out), ep_game_col, ep_theme_col, bp_game_col

stats_df, ep_game_col_used, ep_theme_col_used, bp_game_col_used = supplier_join_stats(ep_df, bp_df, suppliers=('igt', 'everi'))

print(f"Join key used: EP [{ep_game_col_used}] -> BP [{bp_game_col_used}]")
print(f"Theme identifier used on EP side: {ep_theme_col_used}")
print()
display(stats_df)

Join key used: EP [game_name] -> BP [Theme Name]
Theme identifier used on EP side: game_name

,supplier,ep_rows,ep_unique_theme_universe,left_only_unique,left_only_pct,inner_unique,inner_pct,right_only_unique_bp_names,right_only_pct_vs_ep_universe
0,igt,545317,3165,3118,98.515008,47,1.484992,393,12.417062
1,everi,114386,800,791,98.875000,9,1.125000,431,53.875000

In [ ]:
from pathlib import Path

# Export unique theme names from EP/BP filtered to IGT/Everi

def _find_col(df, candidates):
    lookup = {str(c).strip().lower(): c for c in df.columns}
    for c in candidates:
        key = c.strip().lower()
        if key in lookup:
            return lookup[key]
    return None

# Resolve key columns
ep_supplier_col = _find_col(ep_df, ['supplier'])
ep_theme_col = _find_col(ep_df, ['themename', 'theme_name', 'theme name', 'game_name', 'game name'])
ep_release_col = _find_col(ep_df, ['game_release_date', 'game release date', 'release_date', 'release date'])

bp_vendor_col = _find_col(bp_df, ['vendor', 'supplier'])
bp_theme_col = _find_col(bp_df, ['Theme Name', 'theme_name', 'theme name', 'Game Name', 'game_name', 'game name'])

if not ep_supplier_col or not ep_theme_col or not bp_theme_col:
    raise KeyError('Required EP/BP columns not found for unique-theme export.')

# Filter to IGT + Everi
ep_filtered = ep_df[ep_df[ep_supplier_col].astype(str).str.strip().str.lower().isin(['igt', 'everi'])].copy()

if bp_vendor_col:
    bp_filtered = bp_df[bp_df[bp_vendor_col].astype(str).str.strip().str.lower().isin(['igt', 'everi'])].copy()
else:
    bp_filtered = bp_df.copy()

# Build EP unique theme-name output with min game release date
ep_filtered['_theme_name_clean'] = ep_filtered[ep_theme_col].astype(str).str.strip()
ep_filtered['_theme_name_clean'] = ep_filtered['_theme_name_clean'].replace('', pd.NA)

if ep_release_col:
    ep_filtered['_release_dt'] = pd.to_datetime(ep_filtered[ep_release_col], errors='coerce')
    ep_unique = (
        ep_filtered.dropna(subset=['_theme_name_clean'])
        .groupby('_theme_name_clean', as_index=False)['_release_dt']
        .min()
        .rename(columns={
            '_theme_name_clean': 'theme_name',
            '_release_dt': 'min_game_release_date'
        })
        .sort_values('theme_name', kind='stable')
        .reset_index(drop=True)
    )
    ep_unique['min_game_release_date'] = ep_unique['min_game_release_date'].dt.strftime('%Y-%m-%d')
else:
    ep_unique = pd.DataFrame({
        'theme_name': sorted(ep_filtered['_theme_name_clean'].dropna().unique())
    })
    ep_unique['min_game_release_date'] = pd.NA

# Build BP unique theme-name output
bp_unique = pd.DataFrame({
    'theme_name': sorted(bp_filtered[bp_theme_col].dropna().astype(str).str.strip().replace('', pd.NA).dropna().unique())
})

# Save in raw data folder
raw_data_dir = Path(r'C:\EveriTools\Workspace\Code\DemandForeCast\Data\raw sample')
raw_data_dir.mkdir(parents=True, exist_ok=True)

ep_out = raw_data_dir / 'ep_filtered_unique_theme_names.csv'
bp_out = raw_data_dir / 'bp_filtered_unique_theme_names.csv'

ep_unique.to_csv(ep_out, index=False)
bp_unique.to_csv(bp_out, index=False)

print(f'EP filtered unique themes: {len(ep_unique)} -> {ep_out}')
print(f'BP filtered unique themes: {len(bp_unique)} -> {bp_out}')
if ep_release_col:
    print(f'Min release date column used: {ep_release_col}')
else:
    print('No EP release-date column found; min_game_release_date left blank.')

display(ep_unique.head())
display(bp_unique.head())

EP filtered unique themes: 3920 -> C:\EveriTools\Workspace\Code\DemandForeCast\Data\raw sample\ep_filtered_unique_theme_names.csv
BP filtered unique themes: 431 -> C:\EveriTools\Workspace\Code\DemandForeCast\Data\raw sample\bp_filtered_unique_theme_names.csv

                                  theme_name
0                            #xl_eval_error#
1  $.25 wof - triple red hot 7's - gold spin
2                             $25000 pyramid
3                                  1.23.3-18
4                              10 play poker

                                 theme_name
0              5X5X5X JACKPOT GEM 3R15L ASC
1  888 EMPRESS MLP ASC CC (888 Panda clone)
2  888 PANDA MLP ASC CC (888 Empress clone)
3                     ARCTIC GODDESS ASC CC
4                      AZTEC ADVENTURES ASC

In [23]:
bp_unique

                                   theme_name
0                5X5X5X JACKPOT GEM 3R15L ASC
1    888 EMPRESS MLP ASC CC (888 Panda clone)
2    888 PANDA MLP ASC CC (888 Empress clone)
3                       ARCTIC GODDESS ASC CC
4                        AZTEC ADVENTURES ASC
..                                        ...
426             ZODIAC DRGN CSH ON RLS ASC CC
427                        ZODIAC LION ASC CC
428             ZODIAC LION CSH ON RLS ASC CC
429        Zhao Cai Zhu Getting Piggy with It
430                    Zhao Cai Zhu Yo Ho Hog

[431 rows x 1 columns]